name: Lean Action CI

on:
  push:
    branches:
      - main
      - nightly-testing
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set TEST_ARGS manually
        run: |
          echo "TEST_ARGS='--wfail --iofail'" >> $GITHUB_ENV
        shell: bash
      - uses: leanprover/lean-action@v1
        with:
          build-args: "--wfail --iofail"
          test-args: "--wfail --iofail"
      - name: "lake exe mk_all --check --module"
        run: |
          set -e
          lake exe mk_all --check --module
      #- name: "lake shake"
      #  run: |
      #    set -e
      #    lake shake --add-public --keep-implied --keep-prefix Cslib
      - name: "checkInitImports"
        run: |
          set -e
          lake exe checkInitImports
      - uses: leanprover-community/lint-style-action@91923b046cc6a468e9ae340f32f8defe586bd08f # 2026-05-12
        with:
          mode: check
